### PR TITLE
no-custom-classname: perf optimization

### LINKED ISSUE #276: [BUG] Poor performance of `no-custom-classname` and `classnames-order`
**Describe the bug**
`no-custom-classname` and `classnames-order` take a very long time to run relative to other rules.

**To Reproduce**
1. Clone https://github.com/flirtual/flirtual
2. Run eslint in apps/frontend/

**Expected behavior**
Execution time more in line with other rules. These two rules account for over 80% (>50s on a fast machine) of our eslint runtime.

**Screenshots**
```
$ TIMING=1 ./node_modules/.bin/eslint src/**/*.ts src/**/*.tsx
Rule                                           | Time (ms) | Relative
:----------------------------------------------|----------:|--------:
tailwindcss/no-custom-classname                | 34219.388 |    55.4%
tailwindcss/classnames-order                   | 17837.675 |    28.9%
prettier/prettier                              |  1704.244 |     2.8%
tailwindcss/no-contradicting-classname         |  1603.051 |     2.6%
tailwindcss/enforces-negative-arbitrary-values |  1420.780 |     2.3%
tailwindcss/enforces-shorthand                 |  1173.931 |     1.9%
import/no-self-import                          |   933.115 |     1.5%
@typescript-eslint/no-floating-promises        |   672.175 |     1.1%
import/export                                  |   305.687 |     0.5%
import/no-named-as-default-member              |   236.529 |     0.4%
```

**Environment (please complete the following information):**
 - OS: macOS 13 (M1 Pro)
 - Softwares + version used:
     -  eslint 8.49.0

**Additional context**
Setting cssFiles to `[]` per #174 makes `no-custom-classname` almost 40% faster, but these rules still take around 40 seconds to run.

**eslint config file or live demo**
- [Reproduction repo](https://github.com/flirtual/flirtual)
- [eslint config](https://github.com/flirtual/flirtual/blob/main/apps/frontend/.eslintrc.js)
- [Base eslint config](https://github.com/ariesclark/eslint-config/blob/master/src/atoms/tailwindcss/index.ts)

### PR DESCRIPTION
**Pull request by XantreDev**
# no-custom-classname: perf optimization

## Description

Reduced both sync IO time and reduced js performance overhead

Fixes #276 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Runned repository tests

**Test Configuration**:

- OS + version: Windows 11
- NPM version: 10.5.0
- Node version: 20.12.0

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by XantreDev** [comment]
Checked in our react-native project
15s -> 2.4s. **6x performance boost**

Before: 
```
✖ 13 problems (0 errors, 13 warnings)

Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
tailwindcss/no-custom-classname         | 15016.088 |    47.9%
@typescript-eslint/no-misused-promises  |  8721.884 |    27.8%
import/no-duplicates                    |  1842.079 |     5.9%
@typescript-eslint/no-floating-promises |   828.843 |     2.6%
tailwindcss/classnames-order            |   809.069 |     2.6%
tailwindcss/enforces-shorthand          |   765.008 |     2.4%
tailwindcss/no-contradicting-classname  |   655.226 |     2.1%
react/no-unstable-nested-components     |   446.134 |     1.4%
unused-imports/no-unused-imports        |   260.493 |     0.8%
jest/no-disabled-tests                  |   246.434 |     0.8%
```

After: 
```
✖ 13 problems (0 errors, 13 warnings)

Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
@typescript-eslint/no-misused-promises  |  8704.810 |    46.5%
tailwindcss/no-custom-classname         |  2405.613 |    12.9%
import/no-duplicates                    |  1930.955 |    10.3%
@typescript-eslint/no-floating-promises |   880.225 |     4.7%
tailwindcss/enforces-shorthand          |   792.588 |     4.2%
tailwindcss/no-contradicting-classname  |   630.478 |     3.4%
tailwindcss/classnames-order            |   576.570 |     3.1%
react/no-unstable-nested-components     |   467.783 |     2.5%
unused-imports/no-unused-imports        |   253.199 |     1.4%
jest/no-disabled-tests                  |   244.996 |     1.3%
```

**Comment by francoismassart** [comment]
Hi @XantreDev,
thank you for contributing to the project,
I just published `eslint-plugin-tailwindcss@3.17.1-beta.0` which contains your fix.

It should be published soon (finally 😅)


`npm i eslint-plugin-tailwindcss@3.17.1-beta.0 -D`

File: lib/util/cssFiles.js [hunk 1]
```diff
@@ -17,27 +22,56 @@ let classnamesFromFiles = [];
...
+  /**
+   * @type {Set<string>}
+   */
+  const filesSet = new Set();
+  for (const { path: file, stats } of files) {
+    filesSet.add(file);
+    if (!stats) {} 
+    // file is not changed -> we do need to do extra work
+    else if (prevEditedTimestamp.get(file) === stats.mtimeMs) {
+      continue;
```
Comment (snyamathi) [inline lib/util/cssFiles.js:46]: @XantreDev @francoismassart This seems to have introduced a regression if the linter takes longer than `cssFilesRefreshRate` to complete.

When iterating through the css files to parse for class names, if the file is unchanged we skip it, meaning that none of the classnames in any of the CSS files are honored.

```
skipping file .../globals.css
{ classnamesFromFiles: [] }
```

File: lib/util/cssFiles.js [hunk 2]
```diff
@@ -17,27 +22,56 @@ let classnamesFromFiles = [];
...
+      if (!filesSet.has(cachedFilePath)) {
+        keysToDelete.push(cachedFilePath);
+      }
+    }
+    for (const key of keysToDelete) {
+      prevEditedTimestamp.delete(key);
+    }
+ }
+  classnamesFromFiles = [...detectedClassnames];
+  return classnamesFromFiles
```
Comment (snyamathi) [inline lib/util/cssFiles.js:74]: This ends up being an empty array since we hit the `file is not changed` block for every file.

File: lib/util/cssFiles.js (hunk 1 above)
Comment (XantreDev) [reply lib/util/cssFiles.js:46]: I see. Detected class names need to be also cached

Comment (XantreDev) [reply lib/util/cssFiles.js:46]: @snyamathi Should it resolve the problem? https://github.com/francoismassart/eslint-plugin-tailwindcss/pull/341

**Comment by RaenonX** [comment]
> HI, for now, I'll revert back to `3.17.0` and publish as a new patch version => `3.17.2`

Thanks! Appreciate your fast response.

**Comment by francoismassart** [comment]
@RaenonX & @snyamathi 
could you try out the latest beta ?

`npm i eslint-plugin-tailwindcss@3.17.3-beta.3 -D`

Changes made: https://github.com/francoismassart/eslint-plugin-tailwindcss/pull/346

Thank you for your feedbacks

**Comment by RaenonX** [comment]
> @RaenonX & @snyamathi could you try out the latest beta ?
> 
> `npm i eslint-plugin-tailwindcss@3.17.3-beta.3 -D`
> 
> Changes made: #346
> 
> Thank you for your feedbacks

@francoismassart Just tested, seems fine on my end.

Ran `yarn add eslint-plugin-tailwindcss@3.17.3-beta.3 -D` then `eslint` with & without clearing the cache.
